version: '3'

services:
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
  
  db:
    image: mysql:8.0.30-debian
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chat
    ports:
      - 3306:3306
    volumes:
      - ./.docker/mysql:/var/lib/mysql